import { ZodMessages } from '~/common/constants'

export const AuthMessages = [
  // SUCCESS MESSAGES
  'AUTH_REGISTRATION_SUCCESS',
  'AUTH_SIGNIN_SUCCESS',
  'AUTH_SIGNOUT_SUCCESS',
  'AUTH_GET_ACCOUNT_INFORMATION_SUCCESS',
  'AUTH_FORGOT_PASSWORD_EMAIL_SENT',
  'AUTH_UPDATE_ACCOUNT_INFORMATION_SUCCESS',
  'AUTH_RESET_PASSWORD_SUCCESS',
  'AUTH_DELETE_ACCOUNT_SUCCESS',
  'AUTH_VERIFY_EMAIL_SUCCESS',

  // ERROR MESSAGES
  'AUTH_INVALID_CREDENTIALS',
  'AUTH_UNAUTHORIZED',
  'AUTH_USERNAME_INVALID',
  'AUTH_PASSWORD_INVALID',
  'AUTH_USER_NOT_FOUND',
  'AUTH_REGISTRATION_FAILED',
  'AUTH_SIGNIN_FAILED',
  'AUTH_SIGNOUT_FAILED',
  'AUTH_USER_NOT_FOUND_OR_UNAUTHORIZED',
  'AUTH_GET_ACCOUNT_INFORMATION_FAILED',
  'AUTH_FORGOT_PASSWORD_FAILED',
  'AUTH_USER_NOT_FOUND_OR_UPDATE_ACCOUNT_INFORMATION_FAILED',
  'AUTH_UPDATE_ACCOUNT_INFORMATION_FAILED',
  'AUTH_USER_NOT_FOUND_OR_RESET_PASSWORD_FAILED',
  'AUTH_RESET_PASSWORD_FAILED',
  'AUTH_OTP_INVALID',
  'AUTH_USER_NOT_FOUND_OR_DELETE_ACCOUNT_FAILED',
  'AUTH_DELETE_ACCOUNT_FAILED',
  'AUTH_VERIFY_CODE_FAILED',
  'AUTH_USER_NOT_FOUND_OR_VERIFY_CODE_FAILED',
  'AUTH_USERNAME_ALREADY_EXISTS',
  'AUTH_EMAIL_ALREADY_EXISTS',

  ...ZodMessages,
] as const
