export const MinioMessage = [
  // SUCCESS MESSAGES
  'MINIO_FILE_UPLOAD_SUCCESS',
  'MINIO_FILE_DOWNLOAD_SUCCESS',
  'MINIO_FILE_DELETE_SUCCESS',
  'MINIO_BUCKET_CREATE_SUCCESS',
  'MINIO_BUCKET_DELETE_SUCCESS',
  'MINIO_GET_PRESIGNED_URL_SUCCESS',
  'MINIO_GET_FILE_METADATA_SUCCESS',

  // ERROR MESSAGES
  'MINIO_FILE_UPLOAD_FAILED',
  'MINIO_FILE_DOWNLOAD_FAILED',
  'MINIO_FILE_DELETE_FAILED',
  'MINIO_BUCKET_CREATE_FAILED',
  'MINIO_BUCKET_DELETE_FAILED',
  'MINIO_GET_PRESIGNED_URL_FAILED',
  'MINIO_GET_FILE_METADATA_FAILED',

  'MINIO_FILE_NOT_FOUND',
  'MINIO_BUCKET_NOT_FOUND',
  'MINIO_INVALID_FILE_FORMAT',
  'MINIO_UNAUTHORIZED',
  'MINIO_CONNECTION_FAILED',
  'MINIO_INTERNAL_ERROR',
  'MINIO_ACCESS_DENIED',
  'MINIO_FILENAME_ALREADY_EXISTS',
] as const
