import { ZodMessages } from '~/common/constants'

export const ACCESS_TOKENS_MESSAGES = [
  // Success
  'ACCESS_TOKENS_CREATE_SUCCESS',
  'ACCESS_TOKENS_UPDATE_SUCCESS',
  'ACCESS_TOKENS_DELETE_SUCCESS',
  'ACCESS_TOKENS_GET_ALL_SUCCESS',
  'ACCESS_TOKENS_GET_ONE_SUCCESS',
  'ACCESS_TOKENS_RENEW_SUCCESS',
  'ACCESS_TOKENS_REVOKE_SUCCESS',

  // ERROR
  'ACCESS_TOKENS_CREATE_FAILED',
  'ACCESS_TOKENS_UPDATE_FAILED',
  'ACCESS_TOKENS_DELETE_FAILED',
  'ACCESS_TOKENS_GET_ALL_FAILED',
  'ACCESS_TOKENS_GET_ONE_FAILED',
  'ACCESS_TOKENS_RENEW_FAILED',
  'ACCESS_TOKENS_REVOKE_FAILED',

  ...ZodMessages,
] as const
